export const ActionTypes = {
    REGISTER_REQUEST:    "REGISTER_REQUEST",
    REGISTER_SUCCESS:    "REGISTER_SUCCESS",
    REGISTER_ERROR:    "REGISTER_ERROR",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR:   "LOGIN_ERROR",

    NEWS_ERROR:   "NEWS_ERROR",
    NEWS_SUCCESS: "NEWS_SUCCESS",
    NEWS_REQUEST: "NEWS_REQUEST",
//--------------------------------
    HIT_REQUEST: "HIT_REQUEST",
    HIT_SUCCESS: "HIT_SUCCESS",
    HIT_ERROR:   "HIT_ERROR",

    GO_TO_DETAILS_SUCCESS: "GO_TO_DETAILS_SUCCESS",
//-------------------------------

//------------------------------------------
    COLLECTION_REQUEST: "COLLECTION_REQUEST",
    COLLECTION_SUCCESS: "COLLECTION_SUCCESS",
    COLLECTION_ERROR:   "COLLECTION_ERROR",

    GET_TO_COLLECTION_REQUEST: "GET_TO_COLLECTION_REQUEST",
    GET_TO_COLLECTION_SUCCESS: "GET_TO_COLLECTION_SUCCESS",
    GET_TO_COLLECTION_ERROR:   "GET_TO_COLLECTION_ERROR",
//--------------------------------------------
    NEWPRODUCT_REQUEST: "NEWPRODUCT_REQUEST",
    NEWPRODUCT_SUCCESS: "NEWPRODUCT_SUCCESS",
    NEWPRODUCT_ERROR:   "NEWPRODUCT_ERROR",

    CAROUSEL_REQUEST: "CAROUSEL_REQUEST",
    CAROUSEL_SUCCESS: "CAROUSEL_SUCCESS",
    CAROUSEL_ERROR:   "CAROUSEL_ERROR",

    BASKET_REQUEST: "BASKET_REQUEST",
    BASKET_SUCCESS: "BASKET_SUCCESS",
    BASKET_ERROR:   "BASKET_ERROR",

    OPEN_BASKET_REQUEST: "OPEN_BASKET_REQUEST",
    OPEN_BASKET_SUCCESS: "OPEN_BASKET_SUCCESS",
    OPEN_BASKET_ERROR:   "OPEN_BASKET_ERROR",

    ABOUT_REQUEST: "ABOUT_REQUEST",
    ABOUT_SUCCESS: "ABOUT_SUCCESS",
    ABOUT_ERROR:   "ABOUT_ERROR",

    GET_FAV_REQUEST: "GET_FAV_REQUEST",
    GET_FAV_SUCCESS: "GET_FAV_SUCCESS",
    GET_FAV_ERROR:   "GET_FAV_ERROR",
    
    POST_FAV_REQUEST: "POST_FAV_REQUEST",
    POST_FAV_SUCCESS: "POST_FAV_SUCCESS",
    POST_FAV_ERROR:   "POST_FAV_ERROR",

    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_ERROR:   "SEARCH_ERROR",

    CATEGORY_REQUEST: "CATEGORY_REQUEST",
    CATEGORY_SUCCESS: "CATEGORY_SUCCESS",
    CATEGORY_ERROR:   "CATEGORY_ERROR",
//---------------PROFILE---------------------
    PROFILE_REQUEST: "PROFILE_REQUEST",
    PROFILE_SUCCESS: "PROFILE_SUCCESS",
    PROFILE_ERROR:   "PROFILE_ERROR",

    PUT_PROFILE_REQUEST: "PUT_PROFILE_REQUEST",
    PUT_PROFILE_SUCCESS: "PUT_PROFILE_SUCCESS",
    PUT_PROFILE_ERROR: "PUT_PROFILE_ERROR",
//---------------END_OF_PROFILE----------------
    CHANGE_NAME: "CHANGE_NAME",

    LOGIN:  "LOGIN",
    LOGOUT: "LOGOUT",
    
    CLEAR_RESPONSE: "CLEAR_RESPONSE",
};
